trigger:
- none
#- master

resources:
- repo: self

variables:
- group: public-npm
- name: vmImageName
  value: 'ubuntu-latest'
- name: envName
  value: 'autonpm'
- name: version-major
  value: '1'
- name: version-minor
  value: '0'

name: $(version-major).$(version-minor).$(rev:r)

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildNpm
    displayName: Build NPM
    pool:
      vmImage: $(vmImageName)
      workspace:
        clean: all
    steps:
    - script: |
        echo "build number - $(Build.BuildNumber)"
      displayName: 'print variables'

    - checkout: self
      clean: "true"
      persistCredentials: "true"

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: 'install'

    - task: Npm@1
      displayName: 'npm version'
      inputs:
        command: custom
        customCommand: 'version "$(Build.BuildNumber)" --no-git-tag-version'

    - task: "Npm@1"
      displayName: "npm pack"
      inputs:
        command: custom
        customCommand: "pack --pack-destination $(Build.ArtifactStagingDirectory)"

    - task: CopyFiles@2
      displayName: 'autonpm copy to artifact'
      inputs:
        SourceFolder: ''
        Contents: |
         src/**
         package.json
         README.md
        TargetFolder: '$(Build.ArtifactStagingDirectory)/autonpm/'

    - publish: $(build.artifactstagingdirectory)
      displayName: publish artifact
      condition: succeededOrFailed()
      artifact: npm

#  - job: GitTag
#    displayName: Add git tag
#    dependsOn: [ BuildNpm ]
#    condition: succeeded()
#    steps:
#    - checkout: self
#      clean: "true"
#      persistCredentials: "true"
#
#    - pwsh: |
#          git config --global user.name "AzureDevOps Agent"
#          git tag "$(Build.BuildNumber)" --force
#          git push origin "$(Build.BuildNumber)" --force
#          Write-Output "Tagging $(Build.Repository.Name) with $(Build.BuildNumber)"
#      displayName:  set git tag

- stage: Production
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Production
    condition: succeeded()
    displayName: Production
    pool:
      vmImage: $(vmImageName)
    environment: $(envName)
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            displayName: "download packages"
            artifact: npm

#          - task: ExtractFiles@1
#            displayName: "unzip packages"
#            inputs:
#              archiveFilePatterns: "$(Pipeline.Workspace)/npm/autonpm-$(Build.BuildNumber).tgz"
#              destinationFolder: "$(Pipeline.Workspace)/npmout/autonpm"
#              cleanDestinationFolder: true
#              overwriteExistingFiles: true

#          - task: Npm@1
#            displayName: 'npm install'
#            inputs:
#              command: 'install'
#              workingDir: '$(Pipeline.Workspace)/npm/autonpm'

          - task: Npm@1
            displayName: 'publish npm'
            inputs:
              command: publish
              workingDir: '$(Pipeline.Workspace)/npm/autonpm'
              publishEndpoint: '$(publish-npm-credentials)'

#          - task: Npm@1
#            displayName: "publish autonpm"
#            inputs:
#              command: "custom"
#              workingDir: "$(Pipeline.Workspace)/npm"
#              customCommand: "publish autonpm-$(Build.BuildNumber).tgz"
#              customEndpoint: '$(publish-npm-credentials)'